# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
uses_tiny_mce :options => {
                              :theme => 'advanced',
                              :theme_advanced_resizing => true,
                              :theme_advanced_resize_horizontal => false,
                              :plugins => %w{ table fullscreen }
                            }

